# Generated by Django 6.0.1 on 2026-06-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('joyi', models.CharField(max_length=150)),
                ('rasm', models.ImageField(upload_to='completed_projects/')),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('uskuna_nomi', models.CharField(blank=True, max_length=200, null=True)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='static')),
                ('ishlab_chiqarilgan_joyi', models.CharField(max_length=34)),
                ('nomi', models.CharField(max_length=67)),
                ('izoh', models.TextField()),
            ],
        ),
    ]
